version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    ports:
      - '3310:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=blade
      - MARIADB_DATABASE=blade
  blade:
    image: docker.io/bitnami/laravel:latest
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=blade
      - DB_DATABASE=blade
    volumes:
      - './chirps:/app'
    depends_on:
      - mariadb